[package]
name = "sorry-im-off-today"
version = "0.1.0"
authors = ["David Sferruzza <david.sferruzza@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
regex = "1.1"
reqwest = "0.9"
slack_api = "0.21"
serde_json = "1.0"

[dependencies.ical]
version = "0.5.*"
default-features = false
features = ["ical"]
